// Code generated by the Lingua Franca compiler from:
// file://home/foobar/149project/src/GyroDisplay.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/149project/src-gen/GyroDisplay"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_display.h"
#include "_gyro.h"
#include "_gyrodisplay_main.h"
typedef enum {
    gyrodisplay_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[gyrodisplay_main],gyrodisplay_main,_lf_number_of_workers,1,3,0,0,8,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _gyrodisplay_main_main_self_t* gyrodisplay_main_self[1];
    SUPPRESS_UNUSED_WARNING(gyrodisplay_main_self);
    _display_self_t* gyrodisplay_display_self[1];
    SUPPRESS_UNUSED_WARNING(gyrodisplay_display_self);
    _gyro_self_t* gyrodisplay_gyro_self[1];
    SUPPRESS_UNUSED_WARNING(gyrodisplay_gyro_self);
    // ***** Start initializing GyroDisplay of class GyroDisplay
    gyrodisplay_main_self[0] = new__gyrodisplay_main();
    gyrodisplay_main_self[0]->base.environment = &envs[gyrodisplay_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[gyrodisplay_main].startup_reactions[startup_reaction_count[gyrodisplay_main]++] = &gyrodisplay_main_self[0]->_lf__reaction_1;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    // Initiaizing timer GyroDisplay.t.
    gyrodisplay_main_self[0]->_lf__t.offset = 0;
    gyrodisplay_main_self[0]->_lf__t.period = MSEC(100);
    // Associate timer with the environment of its parent
    envs[gyrodisplay_main].timer_triggers[timer_triggers_count[gyrodisplay_main]++] = &gyrodisplay_main_self[0]->_lf__t;
    gyrodisplay_main_self[0]->_lf__t.mode = NULL;
    
    gyrodisplay_main_self[0]->_lf__reaction_0.deadline = NEVER;
    gyrodisplay_main_self[0]->_lf__reaction_1.deadline = NEVER;
    gyrodisplay_main_self[0]->_lf__reaction_2.deadline = NEVER;
    gyrodisplay_main_self[0]->_lf__reaction_3.deadline = NEVER;
    gyrodisplay_main_self[0]->_lf__reaction_4.deadline = NEVER;
    {
        // ***** Start initializing GyroDisplay.display of class Display
        gyrodisplay_display_self[0] = new__display();
        gyrodisplay_display_self[0]->base.environment = &envs[gyrodisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_display_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_display_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_display_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_display_self[0]->_lf_line3_width = -2;
        envs[gyrodisplay_main].startup_reactions[startup_reaction_count[gyrodisplay_main]++] = &gyrodisplay_display_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        gyrodisplay_display_self[0]->_lf__reaction_0.deadline = NEVER;
        gyrodisplay_display_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing GyroDisplay.display
    }
    {
        // ***** Start initializing GyroDisplay.gyro of class Gyro
        gyrodisplay_gyro_self[0] = new__gyro();
        gyrodisplay_gyro_self[0]->base.environment = &envs[gyrodisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_gyro_self[0]->_lf_x_width = -2;
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_gyro_self[0]->_lf_y_width = -2;
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_gyro_self[0]->_lf_z_width = -2;
        // width of -2 indicates that it is not a multiport.
        gyrodisplay_gyro_self[0]->_lf_trigger_width = -2;
        envs[gyrodisplay_main].startup_reactions[startup_reaction_count[gyrodisplay_main]++] = &gyrodisplay_gyro_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        gyrodisplay_gyro_self[0]->_lf__reaction_0.deadline = NEVER;
        gyrodisplay_gyro_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing GyroDisplay.gyro
    }
    //***** End initializing GyroDisplay
    // **** Start deferred initialize for GyroDisplay
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of GyroDisplay.
        gyrodisplay_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        gyrodisplay_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &gyrodisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                gyrodisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &gyrodisplay_main_self[0]->_lf_gyro.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of GyroDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of GyroDisplay.
        gyrodisplay_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        gyrodisplay_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &gyrodisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                gyrodisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &gyrodisplay_main_self[0]->_lf_display.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of GyroDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of GyroDisplay.
        gyrodisplay_main_self[0]->_lf__reaction_2.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        gyrodisplay_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &gyrodisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                gyrodisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &gyrodisplay_main_self[0]->_lf_display.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of GyroDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of GyroDisplay.
        gyrodisplay_main_self[0]->_lf__reaction_3.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        gyrodisplay_main_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &gyrodisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                gyrodisplay_main_self[0]->_lf__reaction_3.output_produced[count++] = &gyrodisplay_main_self[0]->_lf_display.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 3 of GyroDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of GyroDisplay.
        gyrodisplay_main_self[0]->_lf__reaction_4.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        gyrodisplay_main_self[0]->_lf__reaction_4.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_4.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &gyrodisplay_main_self[0]->base.allocations);
        gyrodisplay_main_self[0]->_lf__reaction_4.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &gyrodisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                gyrodisplay_main_self[0]->_lf__reaction_4.output_produced[count++] = &gyrodisplay_main_self[0]->_lf_display.line3.is_present;
            }
        }
        
        // ** End initialization for reaction 4 of GyroDisplay
    
        // **** Start deferred initialize for GyroDisplay.display
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of GyroDisplay.display.
            gyrodisplay_display_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of GyroDisplay.display
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of GyroDisplay.display.
            gyrodisplay_display_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of GyroDisplay.display
        
        }
        // **** End of deferred initialize for GyroDisplay.display
        // **** Start deferred initialize for GyroDisplay.gyro
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of GyroDisplay.gyro.
            gyrodisplay_gyro_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of GyroDisplay.gyro
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of GyroDisplay.gyro.
            gyrodisplay_gyro_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            gyrodisplay_gyro_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &gyrodisplay_gyro_self[0]->base.allocations);
            gyrodisplay_gyro_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &gyrodisplay_gyro_self[0]->base.allocations);
            gyrodisplay_gyro_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &gyrodisplay_gyro_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    gyrodisplay_gyro_self[0]->_lf__reaction_1.output_produced[count++] = &gyrodisplay_gyro_self[0]->_lf_x.is_present;
                }
                {
                    gyrodisplay_gyro_self[0]->_lf__reaction_1.output_produced[count++] = &gyrodisplay_gyro_self[0]->_lf_y.is_present;
                }
                {
                    gyrodisplay_gyro_self[0]->_lf__reaction_1.output_produced[count++] = &gyrodisplay_gyro_self[0]->_lf_z.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of GyroDisplay.gyro
        
        }
        // **** End of deferred initialize for GyroDisplay.gyro
    }
    // **** End of deferred initialize for GyroDisplay
    // **** Start non-nested deferred initialize for GyroDisplay
    // Set number of destination reactors for port gyro.trigger.
    // Iterate over range GyroDisplay.gyro.trigger(0,1)->[GyroDisplay.gyro.trigger(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_main_self[src_runtime]->_lf_gyro.trigger._base.num_destinations = 1;
        gyrodisplay_main_self[src_runtime]->_lf_gyro.trigger._base.source_reactor = (self_base_t*)gyrodisplay_main_self[src_runtime];
    }
    // Set number of destination reactors for port display.line0.
    // Iterate over range GyroDisplay.display.line0(0,1)->[GyroDisplay.display.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_main_self[src_runtime]->_lf_display.line0._base.num_destinations = 1;
        gyrodisplay_main_self[src_runtime]->_lf_display.line0._base.source_reactor = (self_base_t*)gyrodisplay_main_self[src_runtime];
    }
    // Set number of destination reactors for port display.line1.
    // Iterate over range GyroDisplay.display.line1(0,1)->[GyroDisplay.display.line1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_main_self[src_runtime]->_lf_display.line1._base.num_destinations = 1;
        gyrodisplay_main_self[src_runtime]->_lf_display.line1._base.source_reactor = (self_base_t*)gyrodisplay_main_self[src_runtime];
    }
    // Set number of destination reactors for port display.line2.
    // Iterate over range GyroDisplay.display.line2(0,1)->[GyroDisplay.display.line2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_main_self[src_runtime]->_lf_display.line2._base.num_destinations = 1;
        gyrodisplay_main_self[src_runtime]->_lf_display.line2._base.source_reactor = (self_base_t*)gyrodisplay_main_self[src_runtime];
    }
    // Set number of destination reactors for port display.line3.
    // Iterate over range GyroDisplay.display.line3(0,1)->[GyroDisplay.display.line3(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_main_self[src_runtime]->_lf_display.line3._base.num_destinations = 1;
        gyrodisplay_main_self[src_runtime]->_lf_display.line3._base.source_reactor = (self_base_t*)gyrodisplay_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range GyroDisplay.gyro.trigger(0,1)->[GyroDisplay.gyro.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of GyroDisplay triggers 1 downstream reactions
            // through port GyroDisplay.gyro.trigger.
            gyrodisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of GyroDisplay, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.gyro.trigger
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_main_self[src_runtime]->base.allocations); 
            gyrodisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges GyroDisplay.gyro.trigger(0,1)->[GyroDisplay.gyro.trigger(0,1)] and GyroDisplay.gyro.trigger(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.gyro.trigger(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port GyroDisplay.gyro.trigger's trigger struct.
                gyrodisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_gyro_self[dst_runtime]->_lf__trigger;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range GyroDisplay.display.line0(0,1)->[GyroDisplay.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of GyroDisplay triggers 1 downstream reactions
            // through port GyroDisplay.display.line0.
            gyrodisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of GyroDisplay, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.display.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_main_self[src_runtime]->base.allocations); 
            gyrodisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges GyroDisplay.display.line0(0,1)->[GyroDisplay.display.line0(0,1)] and GyroDisplay.display.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.display.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port GyroDisplay.display.line0's trigger struct.
                gyrodisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_display_self[dst_runtime]->_lf__line0;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range GyroDisplay.display.line1(0,1)->[GyroDisplay.display.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of GyroDisplay triggers 1 downstream reactions
            // through port GyroDisplay.display.line1.
            gyrodisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of GyroDisplay, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.display.line1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_main_self[src_runtime]->base.allocations); 
            gyrodisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges GyroDisplay.display.line1(0,1)->[GyroDisplay.display.line1(0,1)] and GyroDisplay.display.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.display.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port GyroDisplay.display.line1's trigger struct.
                gyrodisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_display_self[dst_runtime]->_lf__line1;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range GyroDisplay.display.line2(0,1)->[GyroDisplay.display.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 3 of GyroDisplay triggers 1 downstream reactions
            // through port GyroDisplay.display.line2.
            gyrodisplay_main_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 3 of GyroDisplay, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.display.line2
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_main_self[src_runtime]->base.allocations); 
            gyrodisplay_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges GyroDisplay.display.line2(0,1)->[GyroDisplay.display.line2(0,1)] and GyroDisplay.display.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.display.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port GyroDisplay.display.line2's trigger struct.
                gyrodisplay_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_display_self[dst_runtime]->_lf__line2;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range GyroDisplay.display.line3(0,1)->[GyroDisplay.display.line3(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 4 of GyroDisplay triggers 1 downstream reactions
            // through port GyroDisplay.display.line3.
            gyrodisplay_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 4 of GyroDisplay, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.display.line3
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_main_self[src_runtime]->base.allocations); 
            gyrodisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges GyroDisplay.display.line3(0,1)->[GyroDisplay.display.line3(0,1)] and GyroDisplay.display.line3(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.display.line3(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port GyroDisplay.display.line3's trigger struct.
                gyrodisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_display_self[dst_runtime]->_lf__line3;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for GyroDisplay.display
    
    
    
    
    // **** End of non-nested deferred initialize for GyroDisplay.display
    // **** Start non-nested deferred initialize for GyroDisplay.gyro
    
    // For reference counting, set num_destinations for port GyroDisplay.gyro.x.
    // Iterate over range GyroDisplay.gyro.x(0,1)->[GyroDisplay.gyro.x(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_gyro_self[src_runtime]->_lf_x._base.num_destinations = 1;
        gyrodisplay_gyro_self[src_runtime]->_lf_x._base.source_reactor = (self_base_t*)gyrodisplay_gyro_self[src_runtime];
    }
    // For reference counting, set num_destinations for port GyroDisplay.gyro.y.
    // Iterate over range GyroDisplay.gyro.y(0,1)->[GyroDisplay.gyro.y(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_gyro_self[src_runtime]->_lf_y._base.num_destinations = 1;
        gyrodisplay_gyro_self[src_runtime]->_lf_y._base.source_reactor = (self_base_t*)gyrodisplay_gyro_self[src_runtime];
    }
    // For reference counting, set num_destinations for port GyroDisplay.gyro.z.
    // Iterate over range GyroDisplay.gyro.z(0,1)->[GyroDisplay.gyro.z(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        gyrodisplay_gyro_self[src_runtime]->_lf_z._base.num_destinations = 1;
        gyrodisplay_gyro_self[src_runtime]->_lf_z._base.source_reactor = (self_base_t*)gyrodisplay_gyro_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range GyroDisplay.gyro.x(0,1)->[GyroDisplay.gyro.x(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of GyroDisplay.gyro triggers 1 downstream reactions
            // through port GyroDisplay.gyro.x.
            gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of GyroDisplay.gyro, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.gyro.x
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_gyro_self[src_runtime]->base.allocations); 
            gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range GyroDisplay.gyro.y(0,1)->[GyroDisplay.gyro.y(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of GyroDisplay.gyro triggers 1 downstream reactions
            // through port GyroDisplay.gyro.y.
            gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of GyroDisplay.gyro, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.gyro.y
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_gyro_self[src_runtime]->base.allocations); 
            gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range GyroDisplay.gyro.z(0,1)->[GyroDisplay.gyro.z(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of GyroDisplay.gyro triggers 1 downstream reactions
            // through port GyroDisplay.gyro.z.
            gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of GyroDisplay.gyro, allocate an
            // array of trigger pointers for downstream reactions through port GyroDisplay.gyro.z
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &gyrodisplay_gyro_self[src_runtime]->base.allocations); 
            gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges GyroDisplay.gyro.x(0,1)->[GyroDisplay.gyro.x(0,1)] and GyroDisplay.gyro.x(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.gyro.x(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port GyroDisplay.gyro.x has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_main_self[dst_runtime]->_lf_gyro.x_trigger;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges GyroDisplay.gyro.y(0,1)->[GyroDisplay.gyro.y(0,1)] and GyroDisplay.gyro.y(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.gyro.y(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port GyroDisplay.gyro.y has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_main_self[dst_runtime]->_lf_gyro.y_trigger;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges GyroDisplay.gyro.z(0,1)->[GyroDisplay.gyro.z(0,1)] and GyroDisplay.gyro.z(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range GyroDisplay.gyro.z(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port GyroDisplay.gyro.z has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                gyrodisplay_gyro_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &gyrodisplay_main_self[dst_runtime]->_lf_gyro.z_trigger;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for GyroDisplay.gyro
    // **** End of non-nested deferred initialize for GyroDisplay
    // Connect inputs and outputs for reactor GyroDisplay.
    // Connect inputs and outputs for reactor GyroDisplay.display.
    // Connect GyroDisplay.display.line0(0,1)->[GyroDisplay.display.line0(0,1)] to port GyroDisplay.display.line0(0,1)
    // Iterate over ranges GyroDisplay.display.line0(0,1)->[GyroDisplay.display.line0(0,1)] and GyroDisplay.display.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.display.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_display_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&gyrodisplay_main_self[src_runtime]->_lf_display.line0;
        }
    }
    // Connect GyroDisplay.display.line1(0,1)->[GyroDisplay.display.line1(0,1)] to port GyroDisplay.display.line1(0,1)
    // Iterate over ranges GyroDisplay.display.line1(0,1)->[GyroDisplay.display.line1(0,1)] and GyroDisplay.display.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.display.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_display_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&gyrodisplay_main_self[src_runtime]->_lf_display.line1;
        }
    }
    // Connect GyroDisplay.display.line2(0,1)->[GyroDisplay.display.line2(0,1)] to port GyroDisplay.display.line2(0,1)
    // Iterate over ranges GyroDisplay.display.line2(0,1)->[GyroDisplay.display.line2(0,1)] and GyroDisplay.display.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.display.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_display_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&gyrodisplay_main_self[src_runtime]->_lf_display.line2;
        }
    }
    // Connect GyroDisplay.display.line3(0,1)->[GyroDisplay.display.line3(0,1)] to port GyroDisplay.display.line3(0,1)
    // Iterate over ranges GyroDisplay.display.line3(0,1)->[GyroDisplay.display.line3(0,1)] and GyroDisplay.display.line3(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.display.line3(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_display_self[dst_runtime]->_lf_line3 = (_display_line3_t*)&gyrodisplay_main_self[src_runtime]->_lf_display.line3;
        }
    }
    // Connect inputs and outputs for reactor GyroDisplay.gyro.
    // Connect GyroDisplay.gyro.trigger(0,1)->[GyroDisplay.gyro.trigger(0,1)] to port GyroDisplay.gyro.trigger(0,1)
    // Iterate over ranges GyroDisplay.gyro.trigger(0,1)->[GyroDisplay.gyro.trigger(0,1)] and GyroDisplay.gyro.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.gyro.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_gyro_self[dst_runtime]->_lf_trigger = (_gyro_trigger_t*)&gyrodisplay_main_self[src_runtime]->_lf_gyro.trigger;
        }
    }
    // Connect GyroDisplay.gyro.x(0,1)->[GyroDisplay.gyro.x(0,1)] to port GyroDisplay.gyro.x(0,1)
    // Iterate over ranges GyroDisplay.gyro.x(0,1)->[GyroDisplay.gyro.x(0,1)] and GyroDisplay.gyro.x(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.gyro.x(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_main_self[dst_runtime]->_lf_gyro.x = (_gyro_x_t*)&gyrodisplay_gyro_self[src_runtime]->_lf_x;
        }
    }
    // Connect GyroDisplay.gyro.y(0,1)->[GyroDisplay.gyro.y(0,1)] to port GyroDisplay.gyro.y(0,1)
    // Iterate over ranges GyroDisplay.gyro.y(0,1)->[GyroDisplay.gyro.y(0,1)] and GyroDisplay.gyro.y(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.gyro.y(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_main_self[dst_runtime]->_lf_gyro.y = (_gyro_y_t*)&gyrodisplay_gyro_self[src_runtime]->_lf_y;
        }
    }
    // Connect GyroDisplay.gyro.z(0,1)->[GyroDisplay.gyro.z(0,1)] to port GyroDisplay.gyro.z(0,1)
    // Iterate over ranges GyroDisplay.gyro.z(0,1)->[GyroDisplay.gyro.z(0,1)] and GyroDisplay.gyro.z(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range GyroDisplay.gyro.z(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            gyrodisplay_main_self[dst_runtime]->_lf_gyro.z = (_gyro_z_t*)&gyrodisplay_gyro_self[src_runtime]->_lf_z;
        }
    }
    {
    }
    {
    }
    // Add port GyroDisplay.gyro.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[gyrodisplay_main].is_present_fields[0 + count] = &gyrodisplay_main_self[0]->_lf_gyro.trigger.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[gyrodisplay_main]._lf_intended_tag_fields[0 + count] = &gyrodisplay_main_self[0]->_lf_gyro.trigger.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port GyroDisplay.display.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[gyrodisplay_main].is_present_fields[1 + count] = &gyrodisplay_main_self[0]->_lf_display.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[gyrodisplay_main]._lf_intended_tag_fields[1 + count] = &gyrodisplay_main_self[0]->_lf_display.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port GyroDisplay.display.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[gyrodisplay_main].is_present_fields[2 + count] = &gyrodisplay_main_self[0]->_lf_display.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[gyrodisplay_main]._lf_intended_tag_fields[2 + count] = &gyrodisplay_main_self[0]->_lf_display.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port GyroDisplay.display.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[gyrodisplay_main].is_present_fields[3 + count] = &gyrodisplay_main_self[0]->_lf_display.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[gyrodisplay_main]._lf_intended_tag_fields[3 + count] = &gyrodisplay_main_self[0]->_lf_display.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port GyroDisplay.display.line3 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[gyrodisplay_main].is_present_fields[4 + count] = &gyrodisplay_main_self[0]->_lf_display.line3.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[gyrodisplay_main]._lf_intended_tag_fields[4 + count] = &gyrodisplay_main_self[0]->_lf_display.line3.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port GyroDisplay.gyro.x to array of is_present fields.
            envs[gyrodisplay_main].is_present_fields[5 + count] = &gyrodisplay_gyro_self[0]->_lf_x.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port GyroDisplay.gyro.x to array of intended_tag fields.
            envs[gyrodisplay_main]._lf_intended_tag_fields[5 + count] = &gyrodisplay_gyro_self[0]->_lf_x.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port GyroDisplay.gyro.y to array of is_present fields.
            envs[gyrodisplay_main].is_present_fields[5 + count] = &gyrodisplay_gyro_self[0]->_lf_y.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port GyroDisplay.gyro.y to array of intended_tag fields.
            envs[gyrodisplay_main]._lf_intended_tag_fields[5 + count] = &gyrodisplay_gyro_self[0]->_lf_y.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port GyroDisplay.gyro.z to array of is_present fields.
            envs[gyrodisplay_main].is_present_fields[5 + count] = &gyrodisplay_gyro_self[0]->_lf_z.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port GyroDisplay.gyro.z to array of intended_tag fields.
            envs[gyrodisplay_main]._lf_intended_tag_fields[5 + count] = &gyrodisplay_gyro_self[0]->_lf_z.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance GyroDisplay
    {
        gyrodisplay_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        gyrodisplay_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        gyrodisplay_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        gyrodisplay_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        gyrodisplay_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        gyrodisplay_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        gyrodisplay_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        gyrodisplay_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0003LL;
        gyrodisplay_main_self[0]->_lf__reaction_4.chain_id = 1;
        // index is the OR of level 4 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        gyrodisplay_main_self[0]->_lf__reaction_4.index = 0xffffffffffff0004LL;
    
        // Set reaction priorities for ReactorInstance GyroDisplay.display
        {
            gyrodisplay_display_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            gyrodisplay_display_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            gyrodisplay_display_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 5 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            gyrodisplay_display_self[0]->_lf__reaction_1.index = 0xffffffffffff0005LL;
        }
    
    
        // Set reaction priorities for ReactorInstance GyroDisplay.gyro
        {
            gyrodisplay_gyro_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            gyrodisplay_gyro_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            gyrodisplay_gyro_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            gyrodisplay_gyro_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
