// Code generated by the Lingua Franca compiler from:
// file://Users/alex/149project/src/EncoderDisplay.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/alex/149project/src-gen/EncoderDisplay"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_display.h"
#include "_encoders.h"
#include "_encoderdisplay_main.h"
typedef enum {
    encoderdisplay_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[encoderdisplay_main],encoderdisplay_main,_lf_number_of_workers,1,3,0,0,6,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _encoderdisplay_main_main_self_t* encoderdisplay_main_self[1];
    SUPPRESS_UNUSED_WARNING(encoderdisplay_main_self);
    _display_self_t* encoderdisplay_display_self[1];
    SUPPRESS_UNUSED_WARNING(encoderdisplay_display_self);
    _encoders_self_t* encoderdisplay_encoder_self[1];
    SUPPRESS_UNUSED_WARNING(encoderdisplay_encoder_self);
    // ***** Start initializing EncoderDisplay of class EncoderDisplay
    encoderdisplay_main_self[0] = new__encoderdisplay_main();
    encoderdisplay_main_self[0]->base.environment = &envs[encoderdisplay_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[encoderdisplay_main].startup_reactions[startup_reaction_count[encoderdisplay_main]++] = &encoderdisplay_main_self[0]->_lf__reaction_1;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    // Initiaizing timer EncoderDisplay.t.
    encoderdisplay_main_self[0]->_lf__t.offset = 0;
    encoderdisplay_main_self[0]->_lf__t.period = SEC(1);
    // Associate timer with the environment of its parent
    envs[encoderdisplay_main].timer_triggers[timer_triggers_count[encoderdisplay_main]++] = &encoderdisplay_main_self[0]->_lf__t;
    encoderdisplay_main_self[0]->_lf__t.mode = NULL;
    
    encoderdisplay_main_self[0]->_lf__reaction_0.deadline = NEVER;
    encoderdisplay_main_self[0]->_lf__reaction_1.deadline = NEVER;
    encoderdisplay_main_self[0]->_lf__reaction_2.deadline = NEVER;
    encoderdisplay_main_self[0]->_lf__reaction_3.deadline = NEVER;
    {
        // ***** Start initializing EncoderDisplay.display of class Display
        encoderdisplay_display_self[0] = new__display();
        encoderdisplay_display_self[0]->base.environment = &envs[encoderdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_display_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_display_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_display_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_display_self[0]->_lf_line3_width = -2;
        envs[encoderdisplay_main].startup_reactions[startup_reaction_count[encoderdisplay_main]++] = &encoderdisplay_display_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        encoderdisplay_display_self[0]->_lf__reaction_0.deadline = NEVER;
        encoderdisplay_display_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing EncoderDisplay.display
    }
    {
        // ***** Start initializing EncoderDisplay.encoder of class Encoders
        encoderdisplay_encoder_self[0] = new__encoders();
        encoderdisplay_encoder_self[0]->base.environment = &envs[encoderdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_encoder_self[0]->_lf_right_width = -2;
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_encoder_self[0]->_lf_left_width = -2;
        // width of -2 indicates that it is not a multiport.
        encoderdisplay_encoder_self[0]->_lf_trigger_width = -2;
        envs[encoderdisplay_main].startup_reactions[startup_reaction_count[encoderdisplay_main]++] = &encoderdisplay_encoder_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        encoderdisplay_encoder_self[0]->_lf__reaction_0.deadline = NEVER;
        encoderdisplay_encoder_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing EncoderDisplay.encoder
    }
    //***** End initializing EncoderDisplay
    // **** Start deferred initialize for EncoderDisplay
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of EncoderDisplay.
        encoderdisplay_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        encoderdisplay_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &encoderdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                encoderdisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &encoderdisplay_main_self[0]->_lf_encoder.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of EncoderDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of EncoderDisplay.
        encoderdisplay_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        encoderdisplay_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &encoderdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                encoderdisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &encoderdisplay_main_self[0]->_lf_display.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of EncoderDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of EncoderDisplay.
        encoderdisplay_main_self[0]->_lf__reaction_2.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        encoderdisplay_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &encoderdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                encoderdisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &encoderdisplay_main_self[0]->_lf_display.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of EncoderDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of EncoderDisplay.
        encoderdisplay_main_self[0]->_lf__reaction_3.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        encoderdisplay_main_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &encoderdisplay_main_self[0]->base.allocations);
        encoderdisplay_main_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &encoderdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                encoderdisplay_main_self[0]->_lf__reaction_3.output_produced[count++] = &encoderdisplay_main_self[0]->_lf_display.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 3 of EncoderDisplay
    
        // **** Start deferred initialize for EncoderDisplay.display
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of EncoderDisplay.display.
            encoderdisplay_display_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of EncoderDisplay.display
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of EncoderDisplay.display.
            encoderdisplay_display_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of EncoderDisplay.display
        
        }
        // **** End of deferred initialize for EncoderDisplay.display
        // **** Start deferred initialize for EncoderDisplay.encoder
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of EncoderDisplay.encoder.
            encoderdisplay_encoder_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of EncoderDisplay.encoder
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of EncoderDisplay.encoder.
            encoderdisplay_encoder_self[0]->_lf__reaction_1.num_outputs = 2;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            encoderdisplay_encoder_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    2, sizeof(trigger_t**),
                    &encoderdisplay_encoder_self[0]->base.allocations);
            encoderdisplay_encoder_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    2, sizeof(int),
                    &encoderdisplay_encoder_self[0]->base.allocations);
            encoderdisplay_encoder_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    2, sizeof(bool*),
                    &encoderdisplay_encoder_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    encoderdisplay_encoder_self[0]->_lf__reaction_1.output_produced[count++] = &encoderdisplay_encoder_self[0]->_lf_left.is_present;
                }
                {
                    encoderdisplay_encoder_self[0]->_lf__reaction_1.output_produced[count++] = &encoderdisplay_encoder_self[0]->_lf_right.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of EncoderDisplay.encoder
        
        }
        // **** End of deferred initialize for EncoderDisplay.encoder
    }
    // **** End of deferred initialize for EncoderDisplay
    // **** Start non-nested deferred initialize for EncoderDisplay
    {
        // Set number of destination reactors for port encoder.trigger.
        // Iterate over range EncoderDisplay.encoder.trigger(0,1)->[EncoderDisplay.encoder.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_main_self[src_runtime]->_lf_encoder.trigger._base.num_destinations = 1;
            encoderdisplay_main_self[src_runtime]->_lf_encoder.trigger._base.source_reactor = (self_base_t*)encoderdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port display.line0.
        // Iterate over range EncoderDisplay.display.line0(0,1)->[EncoderDisplay.display.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_main_self[src_runtime]->_lf_display.line0._base.num_destinations = 1;
            encoderdisplay_main_self[src_runtime]->_lf_display.line0._base.source_reactor = (self_base_t*)encoderdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port display.line1.
        // Iterate over range EncoderDisplay.display.line1(0,1)->[EncoderDisplay.display.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_main_self[src_runtime]->_lf_display.line1._base.num_destinations = 1;
            encoderdisplay_main_self[src_runtime]->_lf_display.line1._base.source_reactor = (self_base_t*)encoderdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port display.line2.
        // Iterate over range EncoderDisplay.display.line2(0,1)->[EncoderDisplay.display.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_main_self[src_runtime]->_lf_display.line2._base.num_destinations = 1;
            encoderdisplay_main_self[src_runtime]->_lf_display.line2._base.source_reactor = (self_base_t*)encoderdisplay_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range EncoderDisplay.encoder.trigger(0,1)->[EncoderDisplay.encoder.trigger(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of EncoderDisplay triggers 1 downstream reactions
                // through port EncoderDisplay.encoder.trigger.
                encoderdisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of EncoderDisplay, allocate an
                // array of trigger pointers for downstream reactions through port EncoderDisplay.encoder.trigger
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &encoderdisplay_main_self[src_runtime]->base.allocations); 
                encoderdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges EncoderDisplay.encoder.trigger(0,1)->[EncoderDisplay.encoder.trigger(0,1)] and EncoderDisplay.encoder.trigger(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range EncoderDisplay.encoder.trigger(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port EncoderDisplay.encoder.trigger's trigger struct.
                    encoderdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &encoderdisplay_encoder_self[dst_runtime]->_lf__trigger;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range EncoderDisplay.display.line0(0,1)->[EncoderDisplay.display.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of EncoderDisplay triggers 1 downstream reactions
                // through port EncoderDisplay.display.line0.
                encoderdisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of EncoderDisplay, allocate an
                // array of trigger pointers for downstream reactions through port EncoderDisplay.display.line0
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &encoderdisplay_main_self[src_runtime]->base.allocations); 
                encoderdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges EncoderDisplay.display.line0(0,1)->[EncoderDisplay.display.line0(0,1)] and EncoderDisplay.display.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range EncoderDisplay.display.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port EncoderDisplay.display.line0's trigger struct.
                    encoderdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &encoderdisplay_display_self[dst_runtime]->_lf__line0;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range EncoderDisplay.display.line1(0,1)->[EncoderDisplay.display.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 2 of EncoderDisplay triggers 1 downstream reactions
                // through port EncoderDisplay.display.line1.
                encoderdisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of EncoderDisplay, allocate an
                // array of trigger pointers for downstream reactions through port EncoderDisplay.display.line1
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &encoderdisplay_main_self[src_runtime]->base.allocations); 
                encoderdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges EncoderDisplay.display.line1(0,1)->[EncoderDisplay.display.line1(0,1)] and EncoderDisplay.display.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range EncoderDisplay.display.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port EncoderDisplay.display.line1's trigger struct.
                    encoderdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &encoderdisplay_display_self[dst_runtime]->_lf__line1;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range EncoderDisplay.display.line2(0,1)->[EncoderDisplay.display.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 3 of EncoderDisplay triggers 1 downstream reactions
                // through port EncoderDisplay.display.line2.
                encoderdisplay_main_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 3 of EncoderDisplay, allocate an
                // array of trigger pointers for downstream reactions through port EncoderDisplay.display.line2
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &encoderdisplay_main_self[src_runtime]->base.allocations); 
                encoderdisplay_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges EncoderDisplay.display.line2(0,1)->[EncoderDisplay.display.line2(0,1)] and EncoderDisplay.display.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range EncoderDisplay.display.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port EncoderDisplay.display.line2's trigger struct.
                    encoderdisplay_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &encoderdisplay_display_self[dst_runtime]->_lf__line2;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for EncoderDisplay.display
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for EncoderDisplay.display
        // **** Start non-nested deferred initialize for EncoderDisplay.encoder
        {
        
            // For reference counting, set num_destinations for port EncoderDisplay.encoder.right.
            // Iterate over range EncoderDisplay.encoder.right(0,1)->[EncoderDisplay.encoder.right(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                encoderdisplay_encoder_self[src_runtime]->_lf_right._base.num_destinations = 1;
                encoderdisplay_encoder_self[src_runtime]->_lf_right._base.source_reactor = (self_base_t*)encoderdisplay_encoder_self[src_runtime];
            }
            // For reference counting, set num_destinations for port EncoderDisplay.encoder.left.
            // Iterate over range EncoderDisplay.encoder.left(0,1)->[EncoderDisplay.encoder.left(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                encoderdisplay_encoder_self[src_runtime]->_lf_left._base.num_destinations = 1;
                encoderdisplay_encoder_self[src_runtime]->_lf_left._base.source_reactor = (self_base_t*)encoderdisplay_encoder_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range EncoderDisplay.encoder.left(0,1)->[EncoderDisplay.encoder.left(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of EncoderDisplay.encoder triggers 1 downstream reactions
                    // through port EncoderDisplay.encoder.left.
                    encoderdisplay_encoder_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of EncoderDisplay.encoder, allocate an
                    // array of trigger pointers for downstream reactions through port EncoderDisplay.encoder.left
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &encoderdisplay_encoder_self[src_runtime]->base.allocations); 
                    encoderdisplay_encoder_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range EncoderDisplay.encoder.right(0,1)->[EncoderDisplay.encoder.right(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of EncoderDisplay.encoder triggers 1 downstream reactions
                    // through port EncoderDisplay.encoder.right.
                    encoderdisplay_encoder_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of EncoderDisplay.encoder, allocate an
                    // array of trigger pointers for downstream reactions through port EncoderDisplay.encoder.right
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &encoderdisplay_encoder_self[src_runtime]->base.allocations); 
                    encoderdisplay_encoder_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges EncoderDisplay.encoder.left(0,1)->[EncoderDisplay.encoder.left(0,1)] and EncoderDisplay.encoder.left(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range EncoderDisplay.encoder.left(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port EncoderDisplay.encoder.left has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        encoderdisplay_encoder_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &encoderdisplay_main_self[dst_runtime]->_lf_encoder.left_trigger;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 1;
                // Iterate over ranges EncoderDisplay.encoder.right(0,1)->[EncoderDisplay.encoder.right(0,1)] and EncoderDisplay.encoder.right(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range EncoderDisplay.encoder.right(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port EncoderDisplay.encoder.right has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        encoderdisplay_encoder_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &encoderdisplay_main_self[dst_runtime]->_lf_encoder.right_trigger;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for EncoderDisplay.encoder
    }
    // **** End of non-nested deferred initialize for EncoderDisplay
    // Connect inputs and outputs for reactor EncoderDisplay.
    // Connect inputs and outputs for reactor EncoderDisplay.display.
    // Connect EncoderDisplay.display.line0(0,1)->[EncoderDisplay.display.line0(0,1)] to port EncoderDisplay.display.line0(0,1)
    // Iterate over ranges EncoderDisplay.display.line0(0,1)->[EncoderDisplay.display.line0(0,1)] and EncoderDisplay.display.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range EncoderDisplay.display.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_display_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&encoderdisplay_main_self[src_runtime]->_lf_display.line0;
        }
    }
    // Connect EncoderDisplay.display.line1(0,1)->[EncoderDisplay.display.line1(0,1)] to port EncoderDisplay.display.line1(0,1)
    // Iterate over ranges EncoderDisplay.display.line1(0,1)->[EncoderDisplay.display.line1(0,1)] and EncoderDisplay.display.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range EncoderDisplay.display.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_display_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&encoderdisplay_main_self[src_runtime]->_lf_display.line1;
        }
    }
    // Connect EncoderDisplay.display.line2(0,1)->[EncoderDisplay.display.line2(0,1)] to port EncoderDisplay.display.line2(0,1)
    // Iterate over ranges EncoderDisplay.display.line2(0,1)->[EncoderDisplay.display.line2(0,1)] and EncoderDisplay.display.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range EncoderDisplay.display.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_display_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&encoderdisplay_main_self[src_runtime]->_lf_display.line2;
        }
    }
    // Connect inputs and outputs for reactor EncoderDisplay.encoder.
    // Connect EncoderDisplay.encoder.trigger(0,1)->[EncoderDisplay.encoder.trigger(0,1)] to port EncoderDisplay.encoder.trigger(0,1)
    // Iterate over ranges EncoderDisplay.encoder.trigger(0,1)->[EncoderDisplay.encoder.trigger(0,1)] and EncoderDisplay.encoder.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range EncoderDisplay.encoder.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_encoder_self[dst_runtime]->_lf_trigger = (_encoders_trigger_t*)&encoderdisplay_main_self[src_runtime]->_lf_encoder.trigger;
        }
    }
    // Connect EncoderDisplay.encoder.right(0,1)->[EncoderDisplay.encoder.right(0,1)] to port EncoderDisplay.encoder.right(0,1)
    // Iterate over ranges EncoderDisplay.encoder.right(0,1)->[EncoderDisplay.encoder.right(0,1)] and EncoderDisplay.encoder.right(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range EncoderDisplay.encoder.right(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_main_self[dst_runtime]->_lf_encoder.right = (_encoders_right_t*)&encoderdisplay_encoder_self[src_runtime]->_lf_right;
        }
    }
    // Connect EncoderDisplay.encoder.left(0,1)->[EncoderDisplay.encoder.left(0,1)] to port EncoderDisplay.encoder.left(0,1)
    // Iterate over ranges EncoderDisplay.encoder.left(0,1)->[EncoderDisplay.encoder.left(0,1)] and EncoderDisplay.encoder.left(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range EncoderDisplay.encoder.left(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            encoderdisplay_main_self[dst_runtime]->_lf_encoder.left = (_encoders_left_t*)&encoderdisplay_encoder_self[src_runtime]->_lf_left;
        }
    }
    {
    }
    {
    }
    // Add port EncoderDisplay.encoder.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[encoderdisplay_main].is_present_fields[0 + count] = &encoderdisplay_main_self[0]->_lf_encoder.trigger.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[encoderdisplay_main]._lf_intended_tag_fields[0 + count] = &encoderdisplay_main_self[0]->_lf_encoder.trigger.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port EncoderDisplay.display.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[encoderdisplay_main].is_present_fields[1 + count] = &encoderdisplay_main_self[0]->_lf_display.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[encoderdisplay_main]._lf_intended_tag_fields[1 + count] = &encoderdisplay_main_self[0]->_lf_display.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port EncoderDisplay.display.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[encoderdisplay_main].is_present_fields[2 + count] = &encoderdisplay_main_self[0]->_lf_display.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[encoderdisplay_main]._lf_intended_tag_fields[2 + count] = &encoderdisplay_main_self[0]->_lf_display.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port EncoderDisplay.display.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[encoderdisplay_main].is_present_fields[3 + count] = &encoderdisplay_main_self[0]->_lf_display.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[encoderdisplay_main]._lf_intended_tag_fields[3 + count] = &encoderdisplay_main_self[0]->_lf_display.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port EncoderDisplay.encoder.right to array of is_present fields.
            envs[encoderdisplay_main].is_present_fields[4 + count] = &encoderdisplay_encoder_self[0]->_lf_right.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port EncoderDisplay.encoder.right to array of intended_tag fields.
            envs[encoderdisplay_main]._lf_intended_tag_fields[4 + count] = &encoderdisplay_encoder_self[0]->_lf_right.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port EncoderDisplay.encoder.left to array of is_present fields.
            envs[encoderdisplay_main].is_present_fields[4 + count] = &encoderdisplay_encoder_self[0]->_lf_left.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port EncoderDisplay.encoder.left to array of intended_tag fields.
            envs[encoderdisplay_main]._lf_intended_tag_fields[4 + count] = &encoderdisplay_encoder_self[0]->_lf_left.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance EncoderDisplay
    {
        encoderdisplay_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        encoderdisplay_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        encoderdisplay_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        encoderdisplay_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        encoderdisplay_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        encoderdisplay_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        encoderdisplay_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        encoderdisplay_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0003LL;
    
        // Set reaction priorities for ReactorInstance EncoderDisplay.display
        {
            encoderdisplay_display_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            encoderdisplay_display_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            encoderdisplay_display_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            encoderdisplay_display_self[0]->_lf__reaction_1.index = 0xffffffffffff0004LL;
        }
    
    
        // Set reaction priorities for ReactorInstance EncoderDisplay.encoder
        {
            encoderdisplay_encoder_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            encoderdisplay_encoder_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            encoderdisplay_encoder_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            encoderdisplay_encoder_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
