// Code generated by the Lingua Franca compiler from:
// file://home/foobar/149project/src/ReceiveMessages2.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/149project/src-gen/ReceiveMessages2"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_display.h"
#include "_accelerometer.h"
#include "_receivemessages2_main.h"
typedef enum {
    receivemessages2_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[receivemessages2_main],receivemessages2_main,_lf_number_of_workers,1,3,0,0,6,1,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _receivemessages2_main_main_self_t* receivemessages2_main_self[1];
    SUPPRESS_UNUSED_WARNING(receivemessages2_main_self);
    _display_self_t* receivemessages2_disp_self[1];
    SUPPRESS_UNUSED_WARNING(receivemessages2_disp_self);
    _accelerometer_self_t* receivemessages2_acc_self[1];
    SUPPRESS_UNUSED_WARNING(receivemessages2_acc_self);
    // ***** Start initializing ReceiveMessages2 of class ReceiveMessages2
    receivemessages2_main_self[0] = new__receivemessages2_main();
    receivemessages2_main_self[0]->base.environment = &envs[receivemessages2_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[receivemessages2_main].startup_reactions[startup_reaction_count[receivemessages2_main]++] = &receivemessages2_main_self[0]->_lf__reaction_0;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static bool _initial = false;
        receivemessages2_main_self[0]->led_on = _initial;
    } // End scoping.
    { // For scoping
        static char _initial[100] = "";
        receivemessages2_main_self[0]->reply = _initial;
    } // End scoping.
    { // For scoping
        static char _initial[100] = "";
        receivemessages2_main_self[0]->transmitted_message = _initial;
    } // End scoping.
    { // For scoping
        static char _initial[100] = "";
        receivemessages2_main_self[0]->received_message = _initial;
    } // End scoping.
    { // For scoping
        static char _initial[100] = "";
        receivemessages2_main_self[0]->name = _initial;
    } // End scoping.
    { // For scoping
        static int _initial = 0;
        receivemessages2_main_self[0]->counter = _initial;
    } // End scoping.
    { // For scoping
        static float _initial = 0.0;
        receivemessages2_main_self[0]->x = _initial;
    } // End scoping.
    { // For scoping
        static float _initial = 0.0;
        receivemessages2_main_self[0]->y = _initial;
    } // End scoping.
    // Initiaizing timer ReceiveMessages2.t.
    receivemessages2_main_self[0]->_lf__t.offset = 0;
    receivemessages2_main_self[0]->_lf__t.period = MSEC(50);
    // Associate timer with the environment of its parent
    envs[receivemessages2_main].timer_triggers[timer_triggers_count[receivemessages2_main]++] = &receivemessages2_main_self[0]->_lf__t;
    receivemessages2_main_self[0]->_lf__t.mode = NULL;
    
    receivemessages2_main_self[0]->_lf__reaction_0.deadline = NEVER;
    receivemessages2_main_self[0]->_lf__reaction_1.deadline = NEVER;
    receivemessages2_main_self[0]->_lf__reaction_2.deadline = NEVER;
    // Register for transition handling
    envs[receivemessages2_main].modes->modal_reactor_states[modal_reactor_count[receivemessages2_main]++] = &((self_base_t*)receivemessages2_main_self[0])->_lf__mode_state;
    {
        // ***** Start initializing ReceiveMessages2.disp of class Display
        receivemessages2_disp_self[0] = new__display();
        receivemessages2_disp_self[0]->base.environment = &envs[receivemessages2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        receivemessages2_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        receivemessages2_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        receivemessages2_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        receivemessages2_disp_self[0]->_lf_line3_width = -2;
        envs[receivemessages2_main].startup_reactions[startup_reaction_count[receivemessages2_main]++] = &receivemessages2_disp_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        receivemessages2_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        receivemessages2_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing ReceiveMessages2.disp
    }
    {
        // ***** Start initializing ReceiveMessages2.acc of class Accelerometer
        receivemessages2_acc_self[0] = new__accelerometer();
        receivemessages2_acc_self[0]->base.environment = &envs[receivemessages2_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        receivemessages2_acc_self[0]->_lf_x_width = -2;
        // width of -2 indicates that it is not a multiport.
        receivemessages2_acc_self[0]->_lf_y_width = -2;
        // width of -2 indicates that it is not a multiport.
        receivemessages2_acc_self[0]->_lf_z_width = -2;
        // width of -2 indicates that it is not a multiport.
        receivemessages2_acc_self[0]->_lf_trigger_width = -2;
        envs[receivemessages2_main].startup_reactions[startup_reaction_count[receivemessages2_main]++] = &receivemessages2_acc_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        receivemessages2_acc_self[0]->_lf__reaction_0.deadline = NEVER;
        receivemessages2_acc_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing ReceiveMessages2.acc
    }
    //***** End initializing ReceiveMessages2
    // **** Start deferred initialize for ReceiveMessages2
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of ReceiveMessages2.
        receivemessages2_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of ReceiveMessages2
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of ReceiveMessages2.
        receivemessages2_main_self[0]->_lf__reaction_1.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        receivemessages2_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                3, sizeof(trigger_t**),
                &receivemessages2_main_self[0]->base.allocations);
        receivemessages2_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                3, sizeof(int),
                &receivemessages2_main_self[0]->base.allocations);
        receivemessages2_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                3, sizeof(bool*),
                &receivemessages2_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                receivemessages2_main_self[0]->_lf__reaction_1.output_produced[count++] = &receivemessages2_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                receivemessages2_main_self[0]->_lf__reaction_1.output_produced[count++] = &receivemessages2_main_self[0]->_lf_disp.line1.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                receivemessages2_main_self[0]->_lf__reaction_1.output_produced[count++] = &receivemessages2_main_self[0]->_lf_disp.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of ReceiveMessages2
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of ReceiveMessages2.
        receivemessages2_main_self[0]->_lf__reaction_2.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 2 of ReceiveMessages2
    
        // **** Start deferred initialize for ReceiveMessages2.disp
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ReceiveMessages2.disp.
            receivemessages2_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of ReceiveMessages2.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ReceiveMessages2.disp.
            receivemessages2_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of ReceiveMessages2.disp
        
        }
        // **** End of deferred initialize for ReceiveMessages2.disp
        // **** Start deferred initialize for ReceiveMessages2.acc
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ReceiveMessages2.acc.
            receivemessages2_acc_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of ReceiveMessages2.acc
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ReceiveMessages2.acc.
            receivemessages2_acc_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            receivemessages2_acc_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &receivemessages2_acc_self[0]->base.allocations);
            receivemessages2_acc_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &receivemessages2_acc_self[0]->base.allocations);
            receivemessages2_acc_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &receivemessages2_acc_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    receivemessages2_acc_self[0]->_lf__reaction_1.output_produced[count++] = &receivemessages2_acc_self[0]->_lf_x.is_present;
                }
                {
                    receivemessages2_acc_self[0]->_lf__reaction_1.output_produced[count++] = &receivemessages2_acc_self[0]->_lf_y.is_present;
                }
                {
                    receivemessages2_acc_self[0]->_lf__reaction_1.output_produced[count++] = &receivemessages2_acc_self[0]->_lf_z.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of ReceiveMessages2.acc
        
        }
        // **** End of deferred initialize for ReceiveMessages2.acc
    }
    // **** End of deferred initialize for ReceiveMessages2
    // **** Start non-nested deferred initialize for ReceiveMessages2
    {
        // Set number of destination reactors for port disp.line0.
        // Iterate over range ReceiveMessages2.disp.line0(0,1)->[ReceiveMessages2.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
            receivemessages2_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)receivemessages2_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line1.
        // Iterate over range ReceiveMessages2.disp.line1(0,1)->[ReceiveMessages2.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
            receivemessages2_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)receivemessages2_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line2.
        // Iterate over range ReceiveMessages2.disp.line2(0,1)->[ReceiveMessages2.disp.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_main_self[src_runtime]->_lf_disp.line2._base.num_destinations = 1;
            receivemessages2_main_self[src_runtime]->_lf_disp.line2._base.source_reactor = (self_base_t*)receivemessages2_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range ReceiveMessages2.disp.line0(0,1)->[ReceiveMessages2.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of ReceiveMessages2 triggers 1 downstream reactions
                // through port ReceiveMessages2.disp.line0.
                receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of ReceiveMessages2, allocate an
                // array of trigger pointers for downstream reactions through port ReceiveMessages2.disp.line0
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &receivemessages2_main_self[src_runtime]->base.allocations); 
                receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range ReceiveMessages2.disp.line1(0,1)->[ReceiveMessages2.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of ReceiveMessages2 triggers 1 downstream reactions
                // through port ReceiveMessages2.disp.line1.
                receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of ReceiveMessages2, allocate an
                // array of trigger pointers for downstream reactions through port ReceiveMessages2.disp.line1
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &receivemessages2_main_self[src_runtime]->base.allocations); 
                receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range ReceiveMessages2.disp.line2(0,1)->[ReceiveMessages2.disp.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of ReceiveMessages2 triggers 1 downstream reactions
                // through port ReceiveMessages2.disp.line2.
                receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of ReceiveMessages2, allocate an
                // array of trigger pointers for downstream reactions through port ReceiveMessages2.disp.line2
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &receivemessages2_main_self[src_runtime]->base.allocations); 
                receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges ReceiveMessages2.disp.line0(0,1)->[ReceiveMessages2.disp.line0(0,1)] and ReceiveMessages2.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range ReceiveMessages2.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port ReceiveMessages2.disp.line0's trigger struct.
                    receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &receivemessages2_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges ReceiveMessages2.disp.line1(0,1)->[ReceiveMessages2.disp.line1(0,1)] and ReceiveMessages2.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range ReceiveMessages2.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port ReceiveMessages2.disp.line1's trigger struct.
                    receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &receivemessages2_disp_self[dst_runtime]->_lf__line1;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 2;
            // Iterate over ranges ReceiveMessages2.disp.line2(0,1)->[ReceiveMessages2.disp.line2(0,1)] and ReceiveMessages2.disp.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range ReceiveMessages2.disp.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port ReceiveMessages2.disp.line2's trigger struct.
                    receivemessages2_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &receivemessages2_disp_self[dst_runtime]->_lf__line2;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for ReceiveMessages2.disp
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for ReceiveMessages2.disp
        // **** Start non-nested deferred initialize for ReceiveMessages2.acc
        {
        
            // For reference counting, set num_destinations for port ReceiveMessages2.acc.x.
            // Iterate over range ReceiveMessages2.acc.x(0,1)->[ReceiveMessages2.acc.x(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                receivemessages2_acc_self[src_runtime]->_lf_x._base.num_destinations = 1;
                receivemessages2_acc_self[src_runtime]->_lf_x._base.source_reactor = (self_base_t*)receivemessages2_acc_self[src_runtime];
            }
            // For reference counting, set num_destinations for port ReceiveMessages2.acc.y.
            // Iterate over range ReceiveMessages2.acc.y(0,1)->[ReceiveMessages2.acc.y(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                receivemessages2_acc_self[src_runtime]->_lf_y._base.num_destinations = 1;
                receivemessages2_acc_self[src_runtime]->_lf_y._base.source_reactor = (self_base_t*)receivemessages2_acc_self[src_runtime];
            }
            for (int index486184027c8990b = 0; index486184027c8990b < 1; index486184027c8990b++) { receivemessages2_acc_self[0]->_lf_z._base.source_reactor = (self_base_t*)receivemessages2_acc_self[0]; }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range ReceiveMessages2.acc.x(0,1)->[ReceiveMessages2.acc.x(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of ReceiveMessages2.acc triggers 1 downstream reactions
                    // through port ReceiveMessages2.acc.x.
                    receivemessages2_acc_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of ReceiveMessages2.acc, allocate an
                    // array of trigger pointers for downstream reactions through port ReceiveMessages2.acc.x
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &receivemessages2_acc_self[src_runtime]->base.allocations); 
                    receivemessages2_acc_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range ReceiveMessages2.acc.y(0,1)->[ReceiveMessages2.acc.y(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of ReceiveMessages2.acc triggers 1 downstream reactions
                    // through port ReceiveMessages2.acc.y.
                    receivemessages2_acc_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of ReceiveMessages2.acc, allocate an
                    // array of trigger pointers for downstream reactions through port ReceiveMessages2.acc.y
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &receivemessages2_acc_self[src_runtime]->base.allocations); 
                    receivemessages2_acc_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges ReceiveMessages2.acc.x(0,1)->[ReceiveMessages2.acc.x(0,1)] and ReceiveMessages2.acc.x(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range ReceiveMessages2.acc.x(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port ReceiveMessages2.acc.x has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        receivemessages2_acc_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &receivemessages2_main_self[dst_runtime]->_lf_acc.x_trigger;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 1;
                // Iterate over ranges ReceiveMessages2.acc.y(0,1)->[ReceiveMessages2.acc.y(0,1)] and ReceiveMessages2.acc.y(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range ReceiveMessages2.acc.y(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port ReceiveMessages2.acc.y has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        receivemessages2_acc_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &receivemessages2_main_self[dst_runtime]->_lf_acc.y_trigger;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for ReceiveMessages2.acc
    }
    // **** End of non-nested deferred initialize for ReceiveMessages2
    // Connect inputs and outputs for reactor ReceiveMessages2.
    // Connect inputs and outputs for reactor ReceiveMessages2.disp.
    // Connect ReceiveMessages2.disp.line0(0,1)->[ReceiveMessages2.disp.line0(0,1)] to port ReceiveMessages2.disp.line0(0,1)
    // Iterate over ranges ReceiveMessages2.disp.line0(0,1)->[ReceiveMessages2.disp.line0(0,1)] and ReceiveMessages2.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ReceiveMessages2.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&receivemessages2_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect ReceiveMessages2.disp.line1(0,1)->[ReceiveMessages2.disp.line1(0,1)] to port ReceiveMessages2.disp.line1(0,1)
    // Iterate over ranges ReceiveMessages2.disp.line1(0,1)->[ReceiveMessages2.disp.line1(0,1)] and ReceiveMessages2.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ReceiveMessages2.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&receivemessages2_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    // Connect ReceiveMessages2.disp.line2(0,1)->[ReceiveMessages2.disp.line2(0,1)] to port ReceiveMessages2.disp.line2(0,1)
    // Iterate over ranges ReceiveMessages2.disp.line2(0,1)->[ReceiveMessages2.disp.line2(0,1)] and ReceiveMessages2.disp.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ReceiveMessages2.disp.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_disp_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&receivemessages2_main_self[src_runtime]->_lf_disp.line2;
        }
    }
    // Connect inputs and outputs for reactor ReceiveMessages2.acc.
    // Connect ReceiveMessages2.acc.x(0,1)->[ReceiveMessages2.acc.x(0,1)] to port ReceiveMessages2.acc.x(0,1)
    // Iterate over ranges ReceiveMessages2.acc.x(0,1)->[ReceiveMessages2.acc.x(0,1)] and ReceiveMessages2.acc.x(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ReceiveMessages2.acc.x(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_main_self[dst_runtime]->_lf_acc.x = (_accelerometer_x_t*)&receivemessages2_acc_self[src_runtime]->_lf_x;
        }
    }
    // Connect ReceiveMessages2.acc.y(0,1)->[ReceiveMessages2.acc.y(0,1)] to port ReceiveMessages2.acc.y(0,1)
    // Iterate over ranges ReceiveMessages2.acc.y(0,1)->[ReceiveMessages2.acc.y(0,1)] and ReceiveMessages2.acc.y(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ReceiveMessages2.acc.y(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            receivemessages2_main_self[dst_runtime]->_lf_acc.y = (_accelerometer_y_t*)&receivemessages2_acc_self[src_runtime]->_lf_y;
        }
    }
    
    {
    }
    {
    }
    // Add port ReceiveMessages2.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[receivemessages2_main].is_present_fields[0 + count] = &receivemessages2_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[receivemessages2_main]._lf_intended_tag_fields[0 + count] = &receivemessages2_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port ReceiveMessages2.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[receivemessages2_main].is_present_fields[1 + count] = &receivemessages2_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[receivemessages2_main]._lf_intended_tag_fields[1 + count] = &receivemessages2_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port ReceiveMessages2.disp.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[receivemessages2_main].is_present_fields[2 + count] = &receivemessages2_main_self[0]->_lf_disp.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[receivemessages2_main]._lf_intended_tag_fields[2 + count] = &receivemessages2_main_self[0]->_lf_disp.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port ReceiveMessages2.acc.x to array of is_present fields.
            envs[receivemessages2_main].is_present_fields[3 + count] = &receivemessages2_acc_self[0]->_lf_x.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ReceiveMessages2.acc.x to array of intended_tag fields.
            envs[receivemessages2_main]._lf_intended_tag_fields[3 + count] = &receivemessages2_acc_self[0]->_lf_x.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port ReceiveMessages2.acc.y to array of is_present fields.
            envs[receivemessages2_main].is_present_fields[3 + count] = &receivemessages2_acc_self[0]->_lf_y.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ReceiveMessages2.acc.y to array of intended_tag fields.
            envs[receivemessages2_main]._lf_intended_tag_fields[3 + count] = &receivemessages2_acc_self[0]->_lf_y.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port ReceiveMessages2.acc.z to array of is_present fields.
            envs[receivemessages2_main].is_present_fields[3 + count] = &receivemessages2_acc_self[0]->_lf_z.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ReceiveMessages2.acc.z to array of intended_tag fields.
            envs[receivemessages2_main]._lf_intended_tag_fields[3 + count] = &receivemessages2_acc_self[0]->_lf_z.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance ReceiveMessages2
    {
        receivemessages2_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        receivemessages2_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        receivemessages2_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        receivemessages2_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        receivemessages2_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        receivemessages2_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
    
        // Set reaction priorities for ReactorInstance ReceiveMessages2.disp
        {
            receivemessages2_disp_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            receivemessages2_disp_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            receivemessages2_disp_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            receivemessages2_disp_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
    
    
        // Set reaction priorities for ReactorInstance ReceiveMessages2.acc
        {
            receivemessages2_acc_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            receivemessages2_acc_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            receivemessages2_acc_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            receivemessages2_acc_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
