// Code generated by the Lingua Franca compiler from:
// file://home/foobar/EE149-AutonomousLuminescentChoreography/src/basicComs.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/foobar/EE149-AutonomousLuminescentChoreography/src-gen/basicComs"

#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void _lf_set_default_command_line_options() {}
#include "_display.h"
#include "_basiccoms_main.h"
typedef enum {
    basiccoms_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[basiccoms_main],basiccoms_main,_lf_number_of_workers,1,2,0,0,4,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _basiccoms_main_main_self_t* basiccoms_main_self[1];
    SUPPRESS_UNUSED_WARNING(basiccoms_main_self);
    _display_self_t* basiccoms_disp_self[1];
    SUPPRESS_UNUSED_WARNING(basiccoms_disp_self);
    // ***** Start initializing basicComs of class basicComs
    basiccoms_main_self[0] = new__basiccoms_main();
    basiccoms_main_self[0]->base.environment = &envs[basiccoms_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    envs[basiccoms_main].startup_reactions[startup_reaction_count[basiccoms_main]++] = &basiccoms_main_self[0]->_lf__reaction_0;
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    { // For scoping
        static bool _initial = false;
        basiccoms_main_self[0]->led_on = _initial;
    } // End scoping.
    // Initiaizing timer basicComs.t.
    basiccoms_main_self[0]->_lf__t.offset = 0;
    basiccoms_main_self[0]->_lf__t.period = MSEC(250);
    // Associate timer with the environment of its parent
    envs[basiccoms_main].timer_triggers[timer_triggers_count[basiccoms_main]++] = &basiccoms_main_self[0]->_lf__t;
    basiccoms_main_self[0]->_lf__t.mode = NULL;
    
    basiccoms_main_self[0]->_lf__reaction_0.deadline = NEVER;
    basiccoms_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing basicComs.disp of class Display
        basiccoms_disp_self[0] = new__display();
        basiccoms_disp_self[0]->base.environment = &envs[basiccoms_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        basiccoms_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        basiccoms_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        basiccoms_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        basiccoms_disp_self[0]->_lf_line3_width = -2;
        envs[basiccoms_main].startup_reactions[startup_reaction_count[basiccoms_main]++] = &basiccoms_disp_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        basiccoms_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        basiccoms_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing basicComs.disp
    }
    //***** End initializing basicComs
    // **** Start deferred initialize for basicComs
    {
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of basicComs.
        basiccoms_main_self[0]->_lf__reaction_0.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        basiccoms_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &basiccoms_main_self[0]->base.allocations);
        basiccoms_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &basiccoms_main_self[0]->base.allocations);
        basiccoms_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &basiccoms_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                basiccoms_main_self[0]->_lf__reaction_0.output_produced[count++] = &basiccoms_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                basiccoms_main_self[0]->_lf__reaction_0.output_produced[count++] = &basiccoms_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of basicComs
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of basicComs.
        basiccoms_main_self[0]->_lf__reaction_1.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        basiccoms_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                3, sizeof(trigger_t**),
                &basiccoms_main_self[0]->base.allocations);
        basiccoms_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                3, sizeof(int),
                &basiccoms_main_self[0]->base.allocations);
        basiccoms_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                3, sizeof(bool*),
                &basiccoms_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                basiccoms_main_self[0]->_lf__reaction_1.output_produced[count++] = &basiccoms_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                basiccoms_main_self[0]->_lf__reaction_1.output_produced[count++] = &basiccoms_main_self[0]->_lf_disp.line2.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                basiccoms_main_self[0]->_lf__reaction_1.output_produced[count++] = &basiccoms_main_self[0]->_lf_disp.line3.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of basicComs
    
        // **** Start deferred initialize for basicComs.disp
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of basicComs.disp.
            basiccoms_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of basicComs.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of basicComs.disp.
            basiccoms_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of basicComs.disp
        
        }
        // **** End of deferred initialize for basicComs.disp
    }
    // **** End of deferred initialize for basicComs
    // **** Start non-nested deferred initialize for basicComs
    // Set number of destination reactors for port disp.line0.
    // Iterate over range basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        basiccoms_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
        basiccoms_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)basiccoms_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line1.
    // Iterate over range basicComs.disp.line1(0,1)->[basicComs.disp.line1(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        basiccoms_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
        basiccoms_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)basiccoms_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line2.
    // Iterate over range basicComs.disp.line2(0,1)->[basicComs.disp.line2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        basiccoms_main_self[src_runtime]->_lf_disp.line2._base.num_destinations = 1;
        basiccoms_main_self[src_runtime]->_lf_disp.line2._base.source_reactor = (self_base_t*)basiccoms_main_self[src_runtime];
    }
    // Set number of destination reactors for port disp.line3.
    // Iterate over range basicComs.disp.line3(0,1)->[basicComs.disp.line3(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        basiccoms_main_self[src_runtime]->_lf_disp.line3._base.num_destinations = 1;
        basiccoms_main_self[src_runtime]->_lf_disp.line3._base.source_reactor = (self_base_t*)basiccoms_main_self[src_runtime];
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of basicComs triggers 1 downstream reactions
            // through port basicComs.disp.line0.
            basiccoms_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of basicComs, allocate an
            // array of trigger pointers for downstream reactions through port basicComs.disp.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &basiccoms_main_self[src_runtime]->base.allocations); 
            basiccoms_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range basicComs.disp.line1(0,1)->[basicComs.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of basicComs triggers 1 downstream reactions
            // through port basicComs.disp.line1.
            basiccoms_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of basicComs, allocate an
            // array of trigger pointers for downstream reactions through port basicComs.disp.line1
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &basiccoms_main_self[src_runtime]->base.allocations); 
            basiccoms_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)] and basicComs.disp.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range basicComs.disp.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port basicComs.disp.line0's trigger struct.
                basiccoms_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &basiccoms_disp_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges basicComs.disp.line1(0,1)->[basicComs.disp.line1(0,1)] and basicComs.disp.line1(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range basicComs.disp.line1(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port basicComs.disp.line1's trigger struct.
                basiccoms_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &basiccoms_disp_self[dst_runtime]->_lf__line1;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of basicComs triggers 1 downstream reactions
            // through port basicComs.disp.line0.
            basiccoms_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of basicComs, allocate an
            // array of trigger pointers for downstream reactions through port basicComs.disp.line0
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &basiccoms_main_self[src_runtime]->base.allocations); 
            basiccoms_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range basicComs.disp.line2(0,1)->[basicComs.disp.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of basicComs triggers 1 downstream reactions
            // through port basicComs.disp.line2.
            basiccoms_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of basicComs, allocate an
            // array of trigger pointers for downstream reactions through port basicComs.disp.line2
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &basiccoms_main_self[src_runtime]->base.allocations); 
            basiccoms_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range basicComs.disp.line3(0,1)->[basicComs.disp.line3(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of basicComs triggers 1 downstream reactions
            // through port basicComs.disp.line3.
            basiccoms_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of basicComs, allocate an
            // array of trigger pointers for downstream reactions through port basicComs.disp.line3
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &basiccoms_main_self[src_runtime]->base.allocations); 
            basiccoms_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)] and basicComs.disp.line0(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range basicComs.disp.line0(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port basicComs.disp.line0's trigger struct.
                basiccoms_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &basiccoms_disp_self[dst_runtime]->_lf__line0;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges basicComs.disp.line2(0,1)->[basicComs.disp.line2(0,1)] and basicComs.disp.line2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range basicComs.disp.line2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port basicComs.disp.line2's trigger struct.
                basiccoms_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &basiccoms_disp_self[dst_runtime]->_lf__line2;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges basicComs.disp.line3(0,1)->[basicComs.disp.line3(0,1)] and basicComs.disp.line3(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range basicComs.disp.line3(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port basicComs.disp.line3's trigger struct.
                basiccoms_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &basiccoms_disp_self[dst_runtime]->_lf__line3;
            }
        }
    }
    
    // **** Start non-nested deferred initialize for basicComs.disp
    
    
    
    
    // **** End of non-nested deferred initialize for basicComs.disp
    // **** End of non-nested deferred initialize for basicComs
    // Connect inputs and outputs for reactor basicComs.
    // Connect inputs and outputs for reactor basicComs.disp.
    // Connect basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)] to port basicComs.disp.line0(0,1)
    // Iterate over ranges basicComs.disp.line0(0,1)->[basicComs.disp.line0(0,1)] and basicComs.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range basicComs.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            basiccoms_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&basiccoms_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect basicComs.disp.line1(0,1)->[basicComs.disp.line1(0,1)] to port basicComs.disp.line1(0,1)
    // Iterate over ranges basicComs.disp.line1(0,1)->[basicComs.disp.line1(0,1)] and basicComs.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range basicComs.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            basiccoms_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&basiccoms_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    // Connect basicComs.disp.line2(0,1)->[basicComs.disp.line2(0,1)] to port basicComs.disp.line2(0,1)
    // Iterate over ranges basicComs.disp.line2(0,1)->[basicComs.disp.line2(0,1)] and basicComs.disp.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range basicComs.disp.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            basiccoms_disp_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&basiccoms_main_self[src_runtime]->_lf_disp.line2;
        }
    }
    // Connect basicComs.disp.line3(0,1)->[basicComs.disp.line3(0,1)] to port basicComs.disp.line3(0,1)
    // Iterate over ranges basicComs.disp.line3(0,1)->[basicComs.disp.line3(0,1)] and basicComs.disp.line3(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range basicComs.disp.line3(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            basiccoms_disp_self[dst_runtime]->_lf_line3 = (_display_line3_t*)&basiccoms_main_self[src_runtime]->_lf_disp.line3;
        }
    }
    {
    }
    // Add port basicComs.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[basiccoms_main].is_present_fields[0 + count] = &basiccoms_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[basiccoms_main]._lf_intended_tag_fields[0 + count] = &basiccoms_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port basicComs.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[basiccoms_main].is_present_fields[1 + count] = &basiccoms_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[basiccoms_main]._lf_intended_tag_fields[1 + count] = &basiccoms_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port basicComs.disp.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[basiccoms_main].is_present_fields[2 + count] = &basiccoms_main_self[0]->_lf_disp.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[basiccoms_main]._lf_intended_tag_fields[2 + count] = &basiccoms_main_self[0]->_lf_disp.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port basicComs.disp.line3 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                envs[basiccoms_main].is_present_fields[3 + count] = &basiccoms_main_self[0]->_lf_disp.line3.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                envs[basiccoms_main]._lf_intended_tag_fields[3 + count] = &basiccoms_main_self[0]->_lf_disp.line3.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    
    // Set reaction priorities for ReactorInstance basicComs
    {
        basiccoms_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        basiccoms_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        basiccoms_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        basiccoms_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
    
        // Set reaction priorities for ReactorInstance basicComs.disp
        {
            basiccoms_disp_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            basiccoms_disp_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            basiccoms_disp_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            basiccoms_disp_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
